[OPENBRACK] 
    [LET] [Identifier(x)] [EQUAL] [IntLit(2)] [SEMICOLON] 
    [IF] [Identifier(x)] [GE] [IntLit(3)] [THEN] 
    [OPENBRACK] 
        [LET] [Identifier(y)] [EQUAL] [IntLit(2)] [SEMICOLON] 
        [IntLit(2)] [TIMES] [Identifier(y)] 
    [CLOSEBRACK]
    [ELSE] 
    [OPENBRACK] 
        [LET] [Identifier(y)] [EQUAL] [IntLit(3)] [SEMICOLON] 
        [IntLit(3)] [TIMES] [Identifier(y)] 
    [CLOSEBRACK] 
[CLOSEBRACK] 
[EOF]