[OPENBRACK] 
    [LET] [Identifier(x)] [EQUAL] [IntLit(0)] [SEMICOLON] 
    [WHILE] [Identifier(x)] [LE] [IntLit(5)] 
    [OPENBRACK] 
        [Identifier(x)] [EQUAL] [Identifier(x)] [PLUS] [IntLit(1)] 
    [CLOSEBRACK] [SEMICOLON] 
    [Identifier(x)] 
[CLOSEBRACK] 
[EOF]